<?php

namespace webd\html5;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-04 at 09:15:17.
 */
class TagTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Tag
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Tag;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers webd\html5\Tag::appendChild
     * @todo   Implement testAppendChild().
     */
    public function testAppendChild() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\html5\Tag::getParent
     * @todo   Implement testGetParent().
     */
    public function testGetParent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\html5\Tag::addClass
     * @todo   Implement testAddClass().
     */
    public function testAddClass() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\html5\Tag::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\html5\Tag::tag
     * @todo   Implement testTag().
     */
    public function testTag() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\html5\Tag::id
     * @todo   Implement testId().
     */
    public function testId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\html5\Tag::classes
     * @todo   Implement testClasses().
     */
    public function testClasses() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\html5\Tag::attributes
     * @todo   Implement testAttributes().
     */
    public function testAttributes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\html5\Tag::content
     * @todo   Implement testContent().
     */
    public function testContent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
