<?php

namespace webd\html5;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-05 at 11:08:50.
 */
class TextTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Text
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Text("Test");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers webd\html5\Text::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString() {
        $this->assertEquals("Test", (string) $this->object);
    }

}
